### ISSUE TITLE
博客界面显示异常

### ISSUE THREAD

**Issue by tianyindique** [xnuc/cnblogs-theme-blogure#120]
我是按照readme里一步步复制粘贴的，但是在保存之后，我访问自己的博客，发现出现了以下问题  
#### 1.点击博客右上角“更多”这个按钮，下拉菜单点击没有反应  

![Image](https://github.com/user-attachments/assets/94328e2f-1acf-4cb7-b545-5e9d8f50f640)

#### 3.控制台出现如下报错

![Image](https://github.com/user-attachments/assets/0c5f6e29-82bf-4ef0-b92f-b13ec617dfab)

我是一个前端小白，问了GPT好久，都不知道该怎么解决

**Comment by debuggedme** [comment]
贴一下你的博客园地址 @tianyindique

**Comment by tianyindique** [comment]
https://www.cnblogs.com/tianyindique

**Comment by debuggedme** [comment]
你好 @tianyindique 

在 `custom.css` 中追加, 希望这对你有用

```css
nav details[role=list][open] summary::before {
  content: none;
}
```

如果问题解决, 请关闭此issue.
